SET search_path TO car_entry_control;

insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (92, false,  'О723ОН439', 'Жигуль', 'Белый');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (946, true,  'У813АН24', 'Жигуль', 'Черный');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (430, true,  'С573СМ651', 'BMW', 'Белый');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (794, false, 'У813АН24', 'Жигуль', 'Красный');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (418, true,  'Н046СВ080', 'Жигуль', 'Красный');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (622, false, 'Т413УВ80', 'Audi', 'Зеленый');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (261, true,  'Н046СВ080', 'Жигуль', 'Синий');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (144, true,  'В200ОМ77', 'BMW', 'Белый');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (188, false, 'У813АН24', 'Жигуль', 'Синий');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (975, false, 'О225КУ73', 'Жигуль', 'Зеленый');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (862, false, 'С600ХУ401', 'Жигуль', 'Синий');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (45, true,   'О723ОН439', 'BMW', 'Белый');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (850, true,  'М217ТВ58', 'Лада', 'Красный');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (891, false, 'О723ОН439', 'Audi', 'Зеленый');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (433, false, 'С573СМ651', 'Лада', 'Черный');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (868, true,  'Т413УВ80', 'Жигуль', 'Синий');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (306, false, 'Т413УВ80', 'Audi', 'Черный');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (104, true,  'У813АН24', 'Жигуль', 'Черный');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (930, false, 'С573СМ651', 'Жигуль', 'Черный');
insert into cars (car_id, car_on_the_territory, government_number, car_model, car_colour) values (641, false, 'С190ХО30', 'Audi', 'Синий');